# Generated by Django 4.2.7 on 2023-11-25 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True, verbose_name='Qurilma ID raqami')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('ministry_id', models.CharField(blank=True, max_length=20, verbose_name='Vazirlikdagi ID raqami')),
                ('permission_to_send', models.BooleanField(default=False, verbose_name="Ma'lumotlar vazirlikka yuborilsinmi?")),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Qurilmadagi sim karta raqami')),
                ('full_height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Suv tubidan sensorgacha balandlik (sm)')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Suv sathi balandligi (sm)')),
                ('height_conf', models.IntegerField(blank=True, default=0, verbose_name='Tuzatish koffitsenti (sm)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Joylashuv (latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Joylashuv (longitude)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_devices', to=settings.AUTH_USER_MODEL, verbose_name='Qurilma egasi')),
            ],
            options={
                'verbose_name': 'Kanal qurilmasi',
                'verbose_name_plural': 'Kanal qurilmalari',
            },
        ),
        migrations.CreateModel(
            name='ChannelMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Joylashuv (latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Joylashuv (longitude)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='main.channeldevice', verbose_name='Kanal qurilmasi')),
            ],
            options={
                'verbose_name': 'Kanal qurilmasi siljish xabari',
                'verbose_name_plural': 'Kanal qurilmasi siljish xabarlari',
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborildimi?')),
                ('h', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Qurilmadan suv yuzigacha balandlik (sm)')),
                ('water_volume', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Suv hajmi (m3/s)')),
                ('bat', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Batareya quvvat darajasi')),
                ('is_charging', models.BooleanField(default=False, verbose_name='Batareya quvvatlanmoqda?')),
                ('net', models.IntegerField(default=0, verbose_name='Tarmoq signal darajasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.channeldevice', verbose_name='Kanal qurilmasi')),
            ],
            options={
                'verbose_name': 'Kanal qurilmasi xabari',
                'verbose_name_plural': 'Kanal qurilmasi xabarlari',
            },
        ),
        migrations.CreateModel(
            name='ChannelDeviceVolumeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tens', models.IntegerField(default=0, verbose_name="O'nlik")),
                ('zero', models.FloatField(default=0, verbose_name='0')),
                ('one', models.FloatField(default=0, verbose_name='1')),
                ('two', models.FloatField(default=0, verbose_name='2')),
                ('three', models.FloatField(default=0, verbose_name='3')),
                ('four', models.FloatField(default=0, verbose_name='4')),
                ('five', models.FloatField(default=0, verbose_name='5')),
                ('six', models.FloatField(default=0, verbose_name='6')),
                ('seven', models.FloatField(default=0, verbose_name='7')),
                ('eight', models.FloatField(default=0, verbose_name='8')),
                ('nine', models.FloatField(default=0, verbose_name='9')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_tables', to='main.channeldevice', verbose_name='Kanal qurilmasi')),
            ],
            options={
                'verbose_name': 'Kanal qurilmasi hajm jadvali',
                'verbose_name_plural': 'Kanal qurilmasi hajm jadvali',
            },
        ),
    ]
